spring:
  h2:
    console:
      enabled: true
      path: /h2
  database:
    url: jdbc:h2:mem:test
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql
      data-locations: classpath*:db/h2/data.sql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
mail:
  address:
    admin: admin@admin.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420