spring:
  h2:
    console:
      enabled: true
      path: /h2
  database:
    url: jdbc:h2:mem:test
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql
      data-locations: classpath*:db/h2/data.sql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE